build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
  armhf: ghcr.io/hassio-addons/base:stable
  armv7: ghcr.io/hassio-addons/base:stable
  i386: ghcr.io/hassio-addons/base:stable
