name: "Ecowitt HTTP Proxy"
description: "An HTTP proxy for Ecowitt weather stations to forward to the Ecowitt integration over HTTPS since Ecowitt does not support HTTPS."
version: "0.1.18"
slug: ecowitt-proxy
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  Webhook_ID: ""
  TCP_Port: 8081
schema:
  Webhook_ID: "match(^[a-fA-F0-9]{32}$)"
  TCP_Port: int
